[package]
name = "chisel"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.1.6", features = ["derive", "cargo"]}
chisel-json = {version = "0.1.18"}
termion = {version = "2.0.1"}
