[package]
name = "chisel"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.1.6", features = ["derive", "cargo"]}
chisel-json = {version = "0.1.18"}
crossterm = {version = "0.26.1"}
atty = {version = "0.2.14"}

[features]
default = ["crossterm"]
crossterm = []
