[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean", "readme"]

[tasks.readme]
command = "cargo"
args = ["readme","-o","README.md"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = []

[tasks.test-release]
command = "cargo"
args = ["test", "--release"]
dependencies = []